#ifndef CS_3210_PROJECT_ASSIGNMENT_ENTITYTYPE_H
#define CS_3210_PROJECT_ASSIGNMENT_ENTITYTYPE_H

/**
 * EntityType.
 */
enum EntityType {
    PLANT,
    HERBIVORE,
    OMNIVORE
};


#endif //CS_3210_PROJECT_ASSIGNMENT_ENTITYTYPE_H
